name: vscode-faker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run compile --if-present
      - run: npm test
